#!/bin/bash
# Job name:
#PBS -N SpMV_perf
# Output files:
#PBS -o ./SpMV_perf.out
# Error files:
#PBS -e ./SpMV_perf.err
# Queue name
#PBS -q short_cpuQ
# Set the maximum wall time

# Set the memory, cpus and resources
#PBS -l select=1:ncpus=64:mem=64gb

# Load modules
module load gcc91 perf
# Select the working directory
cd "$PBS_O_WORKDIR" # go to the directory where qsub was run # Compile and run
g++ -std=c++11 -O3 -march=native -ftree-vectorize src/main.cpp src/matrix.cpp -o src/main.out
MAX_THREADS=64
MATRIX_NAME="${INPUT%.mtx}"
mkdir -p "${MATRIX_NAME}"
BASE="results/${MATRIX_NAME}/${MATRIX_NAME}_perf"
NTHREADS=1
for ((NTHREADS=1; NTHREADS<=MAX_THREADS; NTHREADS*=2)); do
    # Commento iniziale per il file dei risultati
    export OMP_NUM_THREADS=$NTHREADS
    FILENAME="${BASE}_NT${NTHREADS}.txt"
    echo "# Execution with input file: $INPUT" > "${FILENAME}"
    for (( i = 0; i < 10; i++ )); do
        echo "# Execution: $i" >> "${FILENAME}"
        perf stat -e cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,LLC-loads,LLC-load-misses ./src/main.out "$INPUT" 2>> "${FILENAME}"
        echo "" >> "${FILENAME}"
    done
    echo "# END EXECUTION" >> "${FILENAME}"
done
echo "# END OF ALL EXECUTIONS"
