#!/bin/bash
# Job name:
#PBS -N SpMV_cachegrind
# Output files:
#PBS -o ./SpMV_cachegrind.out
# Error files:
#PBS -e ./SpMV_cachegrind.err
# Queue name
#PBS -q short_cpuQ
# Set the maximum wall time

# Set the memory, cpus and resources
#PBS -l select=1:ncpus=64:mem=64gb

# Load modules
module load gcc91
# Select the working directory
cd "$PBS_O_WORKDIR" # go to the directory where qsub was run # Compile and run
g++ -std=c++11 -O3 src/main.cpp src/matrix.cpp -o main.out
MATRIX_NAME="${INPUT%.mtx}"
BASE="results/${MATRIX_NAME}_cachegrind"
CACHE_DIR="results/cachegrind_logs/${MATRIX_NAME}"
# Commento iniziale per il file dei risultati
echo "# Execution with input file: $INPUT" > "${BASE}.txt"
rm -rf "${CACHE_DIR}"
mkdir -p "${CACHE_DIR}"
for (( i = 0; i < 10; i++ )); do
    echo "# Execution: $i" >> "${BASE}.txt"
    # Genera file binario .cg
    valgrind --tool=cachegrind --cachegrind-out-file="${CACHE_DIR}/${MATRIX_NAME}_${i}.cg" ./main.out "$INPUT" >> "${BASE}.txt" 2>&1
    # Converte file .cg (binario) in .txt
    cg_annotate "${CACHE_DIR}/${MATRIX_NAME}_${i}.cg" >> "${BASE}.txt"
    echo "" >> "${BASE}.txt"
done
echo "# END EXECUTION" >> "${BASE}.txt"
