#!/bin/bash
# Job name:
#PBS -N SpMV_runtime
# Output files:
#PBS -o ./SpMV_runtime.out
# Error files:
#PBS -e ./SpMV_runtime.err
# Queue name
#PBS -q short_cpuQ
# Set the maximum wall time

# Set the memory, cpus and resources
#PBS -l select=1:ncpus=64:mem=64gb

# Load modules
module load gcc91
# Select the working directory
cd "$PBS_O_WORKDIR" # go to the directory where qsub was run # Compile and run
g++ -std=c++11 -O3 -march=native -ftree-vectorize src/main.cpp src/matrix.cpp -o src/main.out
MAX_THREADS=64
MATRIX_NAME="${INPUT%.mtx}"
BASE="results/${MATRIX_NAME}"
NTHREADS=1
for ((NTHREADS=1; NTHREADS<=MAX_THREADS; NTHREADS*=2)); do
    export OMP_NUM_THREADS=$NTHREADS
    FILENAME="${BASE}_NT${NTHREADS}.txt"
    # Numero di thread usati
    echo "$NTHREADS" > "${FILENAME}"
    # Commento iniziale per il file dei risultati
    echo "# Execution with input file: $INPUT" >> "${FILENAME}"
    for (( i = 0; i < 100; i++ )); do
        echo "# Execution: $i" >> "${FILENAME}"
        ./src/main.out "$INPUT" >> "${FILENAME}" 2>&1
    done
    echo "# END EXECUTION" >> "${FILENAME}"
done
echo "# END OF ALL EXECUTIONS"
